apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
spec:
  containers:
  - name: posstgres-container
    image: alpine
    command: ['sh','-c', "sleep 1800m"]
    imagePullPolicy: IfNotPresent